version: "1.0"
services:
  HMS-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: Hospital_mgmt
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./HMS-volumes:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=pass"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3307:3306"
      - "33061:33060"

  myphpadmin:
    # image: phpmyadmin/phpmyadmin:latest
    image: phpmyadmin:5.2
    restart: always
    depends_on:
      - HMS-db
    environment:
      PMA_HOST: HMS-db
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "8080:80"

  user-service:
    restart: always
    build:
      context: UserService
    volumes:
      - ./src/main/resources:/app/src/main/resources
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:mysql://HMS-db:3306/Hospital_mgmt
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
    depends_on:
      HMS-db:
        condition: service_healthy
    ports:
      - "9000:9000"

  labtest-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: labtestuser
      POSTGRES_PASSWORD: labtestpassword
      POSTGRES_DB: lab_test_db
    ports:
      - "5432:5432"
    volumes:
      - ./labtest-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labtestuser -d lab_test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  labtest-service:
    build:
      context: LabTestService
    restart: always
    environment:
      - DB_USER=labtestuser
      - DB_PASSWORD=labtestpassword
      - DB_HOST=labtest-db
      - DB_NAME=lab_test_db
    ports:
      - "8000:8000"
    depends_on:
      labtest-db:
        condition: service_healthy