version: "1.0"
services:
  HMS-db:
    image: mysql:latest
    network_mode: "host"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: Hospital_mgmt
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./HMS-volumes:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"

  myphpadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - HMS-db
    environment:
      PMA_HOST: HMS-db
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "8080:80"

  user-service:
    image: user-service-v.1.0.0
    network_mode: "host"
    restart: always
    depends_on:
      HMS-db:
        condition: service_healthy
    ports:
      - 9000:9000

