version: "1.0"
services:
  HMS-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: Hospital_mgmt
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./HMS-volumes:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
      - "33060:33060"

  myphpadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - HMS-db
    environment:
      PMA_HOST: HMS-db
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "8080:80"

  user-service:
    restart: always
    build:
      context: UserService
    volumes:
      - ./src/main/resources:/app/src/main/resources
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:mysql://HMS-db:3306/Hospital_mgmt
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
    depends_on:
      HMS-db:
        condition: service_healthy
    ports:
      - "9000:9000"